players = {
    "1-WHITE":"1-BLANC",
    "1-BLANC":"1-BLANC",
    "2-WHITE":"2-BLANC",
    "2-BLANC":"2-BLANC",
    "3-WHITE":"3-BLANC",
    "3-BLANC":"3-BLANC",
    "4-WHITE":"4-BLANC",
    "4-BLANC":"4-BLANC",
    "5-WHITE":"5-BLANC",
    "5-BLANC":"5-BLANC",
    "6-WHITE":"6-BLANC",
    "6-BLANC":"6-BLANC",
    "7-WHITE":"7-BLANC",
    "7-BLANC":"7-BLANC",
    "1-BLUE":"1-BLEU",
    "1-BLEU": "1-BLEU",
    "2-BLUE":"2-BLEU",
    "2-BLEU": "2-BLEU",
    "3-BLUE":"3-BLEU",
    "3-BLEU": "3-BLEU",
    "4-BLUE":"4-BLEU",
    "4-BLEU": "4-BLEU",
    "5-BLUE":"5-BLEU",
    "5-BLEU": "5-BLEU",
    "6-BLUE":"6-BLEU",
    "6-BLEU": "6-BLEU",
    "7-BLUE":"7-BLEU",
    "7-BLEU": "7-BLEU",
    "1-RED":"1-ROUGE",
    "1-ROUGE": "1-ROUGE",
    "2-RED":"2-ROUGE",
    "2-ROUGE": "2-ROUGE",
    "3-RED":"3-ROUGE",
    "3-ROUGE": "3-ROUGE",
    "4-RED":"4-ROUGE",
    "4-ROUGE": "4-ROUGE",
    "5-RED":"5-ROUGE",
    "5-ROUGE": "5-ROUGE",
    "6-RED":"6-ROUGE",
    "6-ROUGE": "6-ROUGE",
    "7-RED":"7-ROUGE",
    "7-ROUGE": "7-ROUGE",
    "1-GREEN":"1-VERT",
    "1-VERT": "1-VERT",
    "2-GREEN":"2-VERT",
    "2-VERT": "2-VERT",
    "3-GREEN":"3-VERT",
    "3-VERT": "3-VERT",
    "4-GREEN":"4-VERT",
    "4-VERT": "4-VERT",
    "5-GREEN":"5-VERT",
    "5-VERT": "5-VERT",
    "6-GREEN":"6-VERT",
    "6-VERT": "6-VERT",
    "7-GREEN":"7-VERT",
    "7-VERT": "7-VERT"
}


score = {
    "1-BLANC": 0,
    "2-BLANC": 0,
    "3-BLANC": 0,
    "4-BLANC": 0,
    "5-BLANC": 0,
    "6-BLANC": 0,
    "7-BLANC": 0,
    "1-BLEU": 0,
    "2-BLEU": 0,
    "3-BLEU": 0,
    "4-BLEU": 0,
    "5-BLEU": 0,
    "6-BLEU": 0,
    "7-BLEU": 0,
    "1-ROUGE": 0,
    "2-ROUGE": 0,
    "3-ROUGE": 0,
    "4-ROUGE": 0,
    "5-ROUGE": 0,
    "6-ROUGE": 0,
    "7-ROUGE": 0,
    "1-VERT": 0,
    "2-VERT": 0,
    "3-VERT": 0,
    "4-VERT": 0,
    "5-VERT": 0,
    "6-VERT": 0,
    "7-VERT": 0,
}