players = {

    "1-rouge": [
        'r1',
        '1r',
        '1 r',
        '1-rouge',
        '1-rouges',
        'rouge-1',
        'rouge 1',
        '1rouge',
        '1rouges',
        '1 rouge',
        '1 rouges',
        'red-1',
        'red1',
        '1-red',
        '1 red',
        '1red',
        'sandrine',
        'sandrinev',
        'sandrine voyer',
        'sandrinevoyer',
        'sandriner',
        'sandrineroyer',
        'sandrine royer',
        'voyer',
        'royer',
        'sandrine rouge',
        'sandrine rouges'],

    "2-rouge": [
        'r2',
        '2r',
        '2 r',
        '2-rouge',
        '2-rouges',
        'rouge-2',
        'rouge 2',
        '2rouge',
        '2rouges',
        '2 rouge',
        '2 rouges',
        'red-2',
        'red2',
        '2-red',
        '2 red',
        '2red',
        'alexandre-sacha',
        'alex-sacha',
        'alex sacha',
        'sacha',
        'alexandre-sasha',
        'alex-sasha',
        'alex sasha',
        'sasha',
        'alex-sacha simoneau',
        'alex-sasha simoneau',
        'alexandre-sacha simoneau',
        'alexandre-sasha simoneau',
        'simoneau',
        'ass',
        'alex rouge',
        'alex rouges',
        'alex des rouges',
        'alex dans les rouges'
    ],

    "3-rouge": [
        'r3',
        '3r',
        '3 r',
        '3-rouge',
        '3-rouges',
        'rouge-3',
        'rouge 3',
        'red-3',
        'red3',
        '3rouge',
        '3rouges',
        '3 rouge',
        '3 rouges',
        '3-red',
        '3 red',
        '3red',
        'dany',
        'danny',
        'danyb',
        'dany baillargeon',
        'danny baillargeon',
        'danny bailargeon',
        'dany bailargeon',
        'baillargeon',
        'bailargeon',
        'dany rouge',
        'dany rouges',
        'dany dans les rouges'
    ],

    "4-rouge": [
        'r4',
        '4r',
        '4 r',
        '4-rouge',
        '4-rouges',
        'rouge-4',
        'rouge 4',
        'red-4',
        'red4',
        '4rouge',
        '4rouges',
        '4 rouge',
        '4 rouges',
        '4-red',
        '4 red',
        '4red',
        'sabrina',
        'sabrinap',
        'sabp',
        'sabrina pariseau',
        'sabrina parizeau',
        'sab',
        'sab pariseau',
        'sab parizeau',
        'pariseau',
        'parizeau',
        'sabrina rouge',
        'sabrina rouges'
    ],

    "5-rouge": [
        'r5',
        '5r',
        '5 r',
        '5-rouge',
        '5-rouges',
        'rouge-5',
        'rouge 5',
        'red-5',
        'red5',
        '5rouge',
        '5rouges',
        '5 rouge',
        '5 rouges',
        '5-red',
        '5 red',
        '5red',
        'caroline',
        'carolinef',
        'carof',
        'caroline fontaine',
        'caro',
        'caro fontaine',
        'fontaine',
        'caro rouge',
        'caro rouges'
    ],

    "6-rouge": [
        'r6',
        '6r',
        '6 r',
        '6-rouge',
        '6-rouges',
        'rouge-6',
        'rouge 6',
        'red-6',
        'red6',
        '6rouge',
        '6rouges',
        '6 rouge',
        '6 rouges',
        '6-red',
        '6 red',
        '6red',
        'mathieug-t',
        'mathieugt',
        'math garceau',
        'mathieu garceau-t',
        'mathieu garceau-tremblay',
        'matt garceau',
        'mathieu g-t',
        'mathieu g-tremblay',
        'mathieu tremblay',
        'mathieu garceau',
        'matt g-t',
        'g-t',
        'gt',
        'mathieu rouges',
        'mathieu rouge'
    ],

    "7-rouge": [
        'r7',
        '7r',
        '7 r',
        '7-rouge',
        '7-rouges',
        'rouge-7',
        'rouge 7',
        'red-7',
        'red7',
        '7rouge',
        '7rouges',
        '7 rouge',
        '7 rouges',
        '7-red',
        '7 red',
        '7red',
    ],

    "1-vert": [
        'v1',
        '1v',
        '1 v',
        '1-vert',
        '1-verts',
        'vert-1',
        'vert 1',
        'vert-1',
        'green1',
        '1vert',
        '1verts',
        '1 vert',
        '1 verts',
        '1-green',
        '1 green',
        '1green',
    ],

    "2-vert": [
        'v2',
        '2v',
        '2 v',
        '2-vert',
        '2-verts',
        'vert-2',
        'vert 2',
        'vert-2',
        'green2',
        '2vert',
        '2verts',
        '2 vert',
        '2 verts',
        '2-green',
        '2 green',
        '2green',
        'léonie',
        'leonie',
        'léoniea',
        'leoniea',
        'léonie alain',
        'leonie alain',
        'léonie allain',
        'leonie allain',
        'léo',
        'leo',
        'alain',
        'allain',
        'léonnie',
        'leonnie',
        'léonnie alain',
        'leonnie alain',
        'léonnie allain',
        'leonnie allain',
        'léonniea',
        'leonniea',
        'leonie vert',
        'leonie verts',
        'léonie vert',
        'léonie verts'
    ],

    "3-vert": [
        'v3',
        '3v',
        '3 v',
        '3-vert',
        '3-verts',
        'vert-3',
        'vert 3',
        'vert-3',
        'green3',
        '3vert',
        '3verts',
        '3 vert',
        '3 verts',
        '3-green',
        '3 green',
        '3green',
        'félixb',
        'felixb',
        'félix b',
        'felix b',
        'félix boudreault',
        'felix boudreault',
        'félix boudrault',
        'felix boudrault',
        'félix boudreaut',
        'felix boudreaut',
        'boudreault',
        'boudrault',
        'boudreaut',
        'hombre',
        'félix vert',
        'felix vert',
        'félix verts',
        'felix verts'
    ],

    "4-vert": [
        'v4',
        '4v',
        '4 v',
        '4-vert',
        '4-verts',
        'vert-4',
        'vert 4',
        'vert-4',
        'green4',
        '4vert',
        '4verts',
        '4 vert',
        '4 verts',
        '4-green',
        '4 green',
        '4green',
        'simont',
        'simon t',
        'simon turcotte',
        'simon turbo',
        'simon turbo turcotte',
        'turbo turcotte',
        'turbo',
        'simon vert',
        'simon verts'
    ],

    "5-vert": [
        'v5',
        '5v',
        '5 v',
        '5-vert',
        '5-verts',
        'vert-5',
        'vert 5',
        'vert-5',
        'green5',
        '5vert',
        '5verts',
        '5 vert',
        '5 verts',
        '5-green',
        '5 green',
        '5green',
        'mathieum',
        'mathieu m',
        'mathieu muir',
        'mat muir',
        'math muir',
        'mathmuir',
        'matmuir',
        'mathm',
        'matm',
        'muir',
        'muir vert',
        'muir verts'
    ],

    "6-vert": [
        'v6',
        '6v',
        '6 v',
        '6-vert',
        '6-verts',
        'vert-6',
        'vert 6',
        'vert-6',
        'green6',
        '6vert',
        '6verts',
        '6 vert',
        '6 verts',
        '6-green',
        '6 green',
        '6green',
        'mathieug',
        'matg',
        'mathg',
        'mathieu grondin',
        'matgrondin',
        'mathgrondin',
        'mat grondin',
        'math grondin',
        'grondin',
        'grondin vert',
        'grondin verts'
    ],

    "7-vert": [
        'v7',
        '7v',
        '7 v',
        '7-vert',
        '7-verts',
        'vert-7',
        'vert 7',
        'vert-7',
        'green7',
        '7vert',
        '7verts',
        '7 vert',
        '7 verts',
        '7-green',
        '7 green',
        '7green',
        'alexandra',
        'alexandra schmidt',
        'alexandra c schmidt',
        'alex shmidt',
        'alex c schmidt',
        'alexe schmidt',
        'alexe c shmidt',
        'alexandra schmitt',
        'alexandra c schmitt',
        'alexandra schmit',
        'alexandra c schmit',
        'alexandra shmitt',
        'alexandra c shmitt',
        'alexandra chmidt',
        'alexandra c chmidt',
        'alexandra vert',
        'alexandra verts'
    ],

    "1-bleu": [
        'b1',
        '1b',
        '1 b',
        '1-bleu',
        '1-bleus',
        'bleu-1',
        'bleu 1',
        'bleu-1',
        'blue1',
        '1bleu',
        '1bleus',
        '1 bleu',
        '1 bleus',
        '1-blue',
        '1 blue',
        '1blue',
        'élodie',
        'elodie',
        'élodie turcotte',
        'elodie turcotte',
        'élodiet',
        'elodiet',
        'élot',
        'elot',
        'élo',
        'elo',
        'élo turcotte',
        'éloturcotte',
        'eloturcotte',
        'elo turcotte',
        'elodie bleu',
        'élodie bleu',
        'elodie bleus',
        'élodie bleus'
    ],

    "2-bleu": [
        'b2',
        '2b',
        '2 b',
        '2-bleu',
        '2-bleus',
        'bleu-2',
        'bleu 2',
        'bleu-2',
        'blue2',
        '2bleu',
        '2bleus',
        '2 bleu',
        '2 bleus',
        '2-blue',
        '2 blue',
        '2blue',
        'andréanne',
        'andreanne',
        'andréanne chagnon',
        'andreanne chagnon',
        'andréannec',
        'andreannec',
        'andréannechagnon',
        'andreannechagnon',
        'andréane',
        'andreane',
        'chagnon',
        'dred',
        'dredd',
        'andréanne bleu',
        'andreanne bleu',
        'andréanne bleus',
        'andreanne bleus'
    ],

    "3-bleu": [
        'b3',
        '3b',
        '3 b',
        '3-bleu',
        '3-bleus',
        'bleu-3',
        'bleu 3',
        'bleu-3',
        'blue3',
        '3bleu',
        '3bleus',
        '3 bleu',
        '3 bleus',
        '3-blue',
        '3 blue',
        '3blue'
    ],

    "4-bleu": [
        'b4',
        '4b',
        '4 b',
        '4-bleu',
        '4-bleus',
        'bleu-4',
        'bleu 4',
        'bleu-4',
        'blue4',
        '4bleu',
        '4bleus',
        '4 bleu',
        '4 bleus',
        '4-blue',
        '4 blue',
        '4blue',
        'anne-sophie',
        'anne-so',
        'anne-sophie dozois',
        'anne-so dozois',
        'anne sophie',
        'annesophie',
        'anne so',
        'anneso',
        'annesophied',
        'annesophiedozois',
        'annesod',
        'dozois',
        'anso',
        'anso',
        'anne-sophie bleu',
        'anne-sophie bleus',
        'anne sophie bleu',
        'anne sophie bleus'
    ],

    "5-bleu": [
        'b5',
        '5b',
        '5 b',
        '5-bleu',
        '5-bleus',
        'bleu-5',
        'bleu 5',
        'bleu-5',
        'blue5',
        '5bleu',
        '5bleus',
        '5 bleu',
        '5 bleus',
        '5-blue',
        '5 blue',
        '5blue',
        'simonc',
        'simon courchesne',
        'simon courchene',
        'simoncourchesne',
        'simoncourchene',
        'courchesne',
        'courchene',
        'simon bleu',
        'simon bleus'
    ],

    "6-bleu": [
        'b6',
        '6b',
        '6 b',
        '6-bleu',
        '6-bleus',
        'bleu-6',
        'bleu 6',
        'bleu-6',
        'blue6',
        '6bleu',
        '6bleus',
        '6 bleu',
        '6 bleus',
        '6-blue',
        '6 blue',
        '6blue',
        'jean-gabriel',
        'jean-gab',
        'jean gabriel',
        'jean-gabriel morin',
        'jean gabriel morin',
        'jean-gab',
        'jean gab',
        'jean-gab morin',
        'jean gab morin',
        'jeangabriel',
        'jeangabrielm',
        'jeangabrielmorin',
        'j-gab',
        'j gab',
        'j gab morin',
        'j-gab morin',
        'joung',
        'jenga',
        'morin',
        'jean gabriel bleu',
        'jean gabriel bleus',
        'jean-gabriel bleu',
        'jean-gabriel bleus'
    ],

    "7-bleu": [
        'b7',
        '7b',
        '7 b',
        '7-bleu',
        '7-bleus',
        'bleu-7',
        'bleu 7',
        'bleu-7',
        'blue7',
        '7bleu',
        '7bleus',
        '7 bleu',
        '7 bleus',
        '7-blue',
        '7 blue',
        '7blue',
        'félixa',
        'felixa',
        'félix auger',
        'felix auger',
        'félixauger',
        'felixauger',
        'auger',
        'félix bleu',
        'felix bleu',
        'félix bleus',
        'felix bleus'
    ],

    "1-blanc": [
        'w1',
        '1w',
        '1 w',
        '1-blanc',
        '1-blancs',
        'blanc-1',
        'blanc 1',
        'blanc-1',
        'white1',
        '1blanc',
        '1blancs',
        '1 blanc',
        '1 blancs',
        '1-white',
        '1 white',
        '1white',
        'maxime',
        'maxim',
        'maximer',
        'maximr',
        'maxr',
        'max',
        'maxroy',
        'maxime roy',
        'maxim roy',
        'maximeroy',
        'maximroy',
        'max roy',
        'roy',
        'maxime blanc',
        'maxime blancs',
        'max blanc',
        'max blancs'
    ],

    "2-blanc": [
        'w2',
        '2w',
        '2 w',
        '2-blanc',
        '2-blancs',
        'blanc-2',
        'blanc 2',
        'blanc-2',
        'white2',
        '2blanc',
        '2blancs',
        '2 blanc',
        '2 blancs',
        '2-white',
        '2 white',
        '2white',
        'étienne',
        'etienne',
        'etienned',
        'étienned',
        'étienne desbiens',
        'etienne desbiens',
        'étiennedesbiens',
        'etiennedesbiens',
        'desbiens',
        'étienne blanc',
        'étienne blancs',
        'etienne blanc',
        'etienne blancs'
    ],

    "3-blanc": [
        'w3',
        '3w',
        '3 w',
        '3-blanc',
        '3-blancs',
        'blanc-3',
        'blanc 3',
        'blanc-3',
        'white3',
        '3blanc',
        '3blancs',
        '3 blanc',
        '3 blancs',
        '3-white',
        '3 white',
        '3white',
        'samuel ',
        'samuelf',
        'samuel fleury',
        'sam',
        'samf',
        'samfleury',
        'sam fleury',
        'sam fleu',
        'sam puff',
        'fleury',
        'puff',
        'poff',
        'pof',
        'samuel blanc',
        'samuel blancs',
        'sam blanc',
        'sam blancs'
    ],

    "4-blanc": [
        'w4',
        '4w',
        '4 w',
        '4-blanc',
        '4-blancs',
        'blanc-4',
        'blanc 4',
        'blanc-4',
        'white4',
        '4blanc',
        '4blancs',
        '4 blanc',
        '4 blancs',
        '4-white',
        '4 white',
        '4white',
        'catherine',
        'catheriner',
        'cathr',
        'catherine robert',
        'cath robert',
        'robert',
        'cath',
        'cat robert',
        'cat',
        'catherine blanc',
        'catherine blancs',
        'cath blanc',
        'cath blancs'
    ],

    "5-blanc": [
        'w5',
        '5w',
        '5 w',
        '5-blanc',
        '5-blancs',
        'blanc-5',
        'blanc 5',
        'blanc-5',
        'white5',
        '5blanc',
        '5blancs',
        '5 blanc',
        '5 blancs',
        '5-white',
        '5 white',
        '5white',
        'marc-andré',
        'marc andré',
        'marcandre',
        'marcandré',
        'marc-andréf',
        'marc-andref',
        'marcandréf',
        'marcandref',
        'marcandréfortin',
        'marcandrefortin',
        'marc-andré fortin',
        'marc andré fortin',
        'maf',
        'fortin',
        'marc-andré blanc',
        'marc-andré blancs',
        'marc andré blanc',
        'marc andré blancs',
        'marc-andre blanc',
        'marc-andre blancs',
        'marc andre blanc ',
        'marc andre blancs'
    ],
    "6-blanc": [
        'w6',
        '6w',
        '6 w',
        '6-blanc',
        '6-blancs',
        'blanc-6',
        'blanc 6',
        'blanc-6',
        'white6',
        '6blanc',
        '6blancs',
        '6 blanc',
        '6 blancs',
        '6-white',
        '6 white',
        '6white',
    ],
    "7-blanc": [
        'w7',
        '7w',
        '7 w',
        '7-blanc',
        '7-blancs',
        'blanc-7',
        'blanc 7',
        'blanc-7',
        'white7',
        '7blanc',
        '7blancs',
        '7 blanc',
        '7 blancs',
        '7-white',
        '7 white',
        '7white',
        'alexm',
        'alex',
        'alex martin',
        'alexmartin',
        'alexandre ',
        'alexandre martin',
        'martin',
        'le costaud',
        'costaud',
        'alex blanc',
        'alex blancs',
        'alexandre blanc',
        'alexandre blancs'
    ]
}



score = {
    "1-BLANC": 0,
    "2-BLANC": 0,
    "3-BLANC": 0,
    "4-BLANC": 0,
    "5-BLANC": 0,
    "6-BLANC": 0,
    "7-BLANC": 0,
    "1-BLEU": 0,
    "2-BLEU": 0,
    "3-BLEU": 0,
    "4-BLEU": 0,
    "5-BLEU": 0,
    "6-BLEU": 0,
    "7-BLEU": 0,
    "1-ROUGE": 0,
    "2-ROUGE": 0,
    "3-ROUGE": 0,
    "4-ROUGE": 0,
    "5-ROUGE": 0,
    "6-ROUGE": 0,
    "7-ROUGE": 0,
    "1-VERT": 0,
    "2-VERT": 0,
    "3-VERT": 0,
    "4-VERT": 0,
    "5-VERT": 0,
    "6-VERT": 0,
    "7-VERT": 0,
}